import { db_SCHEMA as user_db_SCHEMA } from "@/prisma/controller/user/index_schema";
import { z } from "zod";

export const db_SCHEMA = z.object({
	id: z.string(),
	private_id: z.string(),
	ipqc_verification: z.string(),
	time_insert_capsule: z.date(),
	line_packaging: z.string(),
	pack_machine_number: z.string(),
	operator_name: z.string(),
	wo_packaging: z.string(),
	wo_assembly: z.string(),
	filling_line: z.string(),
	pallet_number: z.string(),
	quantity_capsule: z.number(),
	quantity_NG: z.number(),
	NG_Reverse: z.number(),
	NG_Foreign: z.number(),
	NG_BrokenCapsule: z.number(),
	NG_WrongCode: z.number(),
	NG_BrokenPVC: z.number(),
	NG_BrokenAlumuniumFilm: z.number(),
	NG_ForeignInTube: z.number(),
	NG_CodeAtTube: z.number(),
	NG_LeakEliquid: z.number(),
	NG_DamageTube: z.number(),
	NG_HadapTerbalik: z.number(),
	NG_MixFlavor: z.number(),
	NG_MixConcentration: z.number(),
	NG_Missjudge: z.number(),
	NG_NoLaserCode: z.number(),
	notes: z.string(),
	createdAt: z.date(),
	createdBy: user_db_SCHEMA.shape.user_id,
	updatedAt: z.date(),
	updatedBy: user_db_SCHEMA.shape.user_id,
	Verification_Date: z.date(),
	Verified_By: user_db_SCHEMA.shape.user_id,
});
