import { db_SCHEMA as user_db_SCHEMA } from "@/prisma/controller/user/index_schema";
import { z } from "zod";

export const db_SCHEMA = z.object({
	id: z.number(),
	heater_qty: z.string(),
	RJR_verification_flavor: z.string(),
	verification_lot: z.string(),
	supplier: z.string(),
	heater_top_cover: z.string(),
	heating_holder: z.string(),
	silicone_1: z.string(),
	tube: z.string(),
	plastic_and_silicone_qty: z.string(),
	thimble: z.string(),
	silicone_3: z.string(),
	silicone_2: z.string(),
	bottom_cover: z.string(),
	ceramic_heater: z.string(),
	finished_product_material_number: z.string(),
	material_code: z.string(),
	heater_puff_WO: z.string(),
	qty: z.number(),
	filling_or_blister_WO: z.string(),
	production_date: z.date(),
	extra_flavor: z.string(),
	remark: z.string(),
	createdAt: z.date(),
	createdBy: user_db_SCHEMA.shape.user_id,
	updatedAt: z.date(),
	updatedBy: user_db_SCHEMA.shape.user_id,
	validatedAt: z.date(),
	validatedBy: user_db_SCHEMA.shape.user_id,
});
