import { db_SCHEMA as user_db_SCHEMA } from "@/prisma/controller/user/index_schema";
import { z } from "zod";

export const db_SCHEMA = z.object({
	id: z.number(),
	private_id: z.string(),
	Pengumuman_Pengiriman_Shipment_Notification: z.string(),
	Customer_PO: z.string(),
	Material_Code_Serial: z.string(),
	Flavor_Concentration_Rasa: z.string(),
	Column1: z.string(),
	Line: z.string(),
	Order_Qty: z.string(),
	Work_Order: z.string(),
	Qty_Work_Order: z.number(),
	Tanggal_Mulai: z.date(),
	MNF_Issue_QTY: z.number(),
	Receipt_Qty_of_Qualified_Product_BUoM: z.number(),
	Unreceived_Qty: z.number(),
	Notes_Catatan: z.string(),
	Inspection_Keramik_Batch_Number: z.string(),
	FAI_InDate: z.date(),
	FAI_Result: z.enum(["OK", "NG"]),
	FAI_ResultDate: z.date(),
	FAI_Inspector: user_db_SCHEMA.shape.user_id,
	Inspection_InDate: z.date(),
	Inspection_Result: z.enum(["OK", "NG"]),
	Inspection_ResultDate: z.date(),
	Inspection_Inspector: user_db_SCHEMA.shape.user_id,
	AltitudeNegatifPressure_InDate: z.date(),
	AltitudeNegatifPressure_Result: z.enum(["OK", "NG"]),
	AltitudeNegatifPressure_ResultDate: z.date(),
	AltitudeNegatifPressure_Inspector: user_db_SCHEMA.shape.user_id,
	Dripping_InDate: z.date(),
	Dripping_Result: z.enum(["OK", "NG"]),
	Dripping_ResultDate: z.date(),
	Dripping_Inspector: user_db_SCHEMA.shape.user_id,
	Shift: z.string(),
	Notes: z.string(),
	createdAt: z.date(),
	createdBy: user_db_SCHEMA.shape.user_id,
	updatedAt: z.date(),
	updatedBy: user_db_SCHEMA.shape.user_id,
});
