import { db_SCHEMA as user_db_SCHEMA } from "@/prisma/controller/user/index_schema";
import { z } from "zod";

export const db_SCHEMA = z.object({
	id: z.number(),
	private_id: z.string(),
	RJR_Verification_Flavor: z.string(),
	Verification_Lot: z.string(),
	Supplier: z.string(),
	Heater_Top_Cover: z.string(),
	Heating_Holder: z.string(),
	Silicone_1: z.string(),
	Tube: z.string(),
	Plastic_Silicone_Qty: z.string(),
	Thimble: z.string(),
	Silicone_3: z.string(),
	Silicone_2: z.string(),
	Bottom_Cover: z.string(),
	Ceramic_Heater: z.string(),
	Nomor_Bahan_Produk_Jadi: z.string(),
	Pengkodean_Bahan: z.string(),
	Heater_puff_WO: z.string(),
	Qty: z.number(),
	PO_Filling_Blister_WO: z.string(),
	Rasa_Ekstra: z.string(),
	Remark: z.string(),
	Prod_Plan: z.date(),
	Taken_From_IQC_status: z.boolean(),
	Taken_From_IQC_date: z.date(),
	Put_On_Production_status: z.boolean(),
	Put_On_Production_date: z.date(),
	Sample_In_status: z.boolean(),
	Sample_In_date: z.date(),
	Sample_Tested_status: z.boolean(),
	Sample_Tested_date: z.date(),
	Sample_Test_Result: z.enum(["OK", "NG"]),
	Tester: user_db_SCHEMA.shape.user_id,
	Tester_Plan: z.string(),
	Verification_status: z.boolean(),
	Verification_date: z.date(),
	Verificator: user_db_SCHEMA.shape.user_id,
	Notes: z.string(),
	createdAt: z.date(),
	createdBy: user_db_SCHEMA.shape.user_id,
	updatedAt: z.date(),
	updatedBy: user_db_SCHEMA.shape.user_id,
});
